"use client";

import { useEffect, useRef, useState } from "react";
import { getTraining, type TrainingResponse } from "@/lib/api";

const LN65 = Math.log(65); // ~4.174, the "knows nothing" baseline

const W = 640;
const H = 300;
const L = 44;
const R = 16;
const T = 16;
const B = 30;

export default function TrainingViz({
  onSample,
  hideSample,
}: {
  // report the current scrubber sample up so a parent can show/carry it
  onSample?: (text: string, step: number) => void;
  hideSample?: boolean;
} = {}) {
  const [data, setData] = useState<TrainingResponse | null>(null);
  const [error, setError] = useState(false);
  const [idx, setIdx] = useState(0);
  const [playing, setPlaying] = useState(false);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    getTraining()
      .then((d) => {
        setData(d);
        setIdx(d.history.length - 1);
      })
      .catch(() => setError(true));
  }, []);

  // surface the current sample to the parent (for the carry into generation)
  useEffect(() => {
    if (!data || !onSample) return;
    onSample(data.samples[idx]?.text ?? "", data.history[idx]?.step ?? 0);
  }, [idx, data, onSample]);

  useEffect(() => {
    if (!playing || !data) return;
    timer.current = setInterval(() => {
      setIdx((i) => {
        if (i >= data.history.length - 1) {
          setPlaying(false);
          return i;
        }
        return i + 1;
      });
    }, 600);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [playing, data]);

  if (error)
    return (
      <p className="text-sm text-amber-700">
        No training history yet — it&apos;s generated by{" "}
        <code className="font-mono">uv run python -m scripts.train</code>.
      </p>
    );
  if (!data) return <p className="text-sm text-stone-400">Loading training run…</p>;

  const { history, samples, config } = data;
  const maxStep = config.max_steps;
  const allLoss = history.flatMap((h) => [h.train, h.val]);
  const yMax = Math.max(...allLoss, LN65 + 0.05);
  const yMin = Math.min(...allLoss) - 0.1;

  const px = (step: number) => L + (step / maxStep) * (W - L - R);
  const py = (loss: number) =>
    T + (1 - (loss - yMin) / (yMax - yMin)) * (H - T - B);

  const line = (key: "train" | "val") =>
    history.map((h) => `${px(h.step)},${py(h[key])}`).join(" ");

  const cur = history[idx];
  const curSample = samples[idx];

  return (
    <div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm">
      <div className="mb-3 flex flex-wrap items-center gap-x-5 gap-y-1 text-sm">
        <span className="flex items-center gap-1.5 text-stone-600">
          <span className="inline-block h-2.5 w-4 rounded bg-rose-500" /> train
          loss
        </span>
        <span className="flex items-center gap-1.5 text-stone-600">
          <span className="inline-block h-2.5 w-4 rounded bg-indigo-500" /> val
          loss
        </span>
        <span className="text-stone-400">
          {config.params.toLocaleString()} parameters
        </span>
      </div>

      <svg viewBox={`0 0 ${W} ${H}`} className="w-full">
        {/* y gridlines + labels */}
        {[1, 2, 3, 4].map((v) => (
          <g key={v}>
            <line
              x1={L}
              y1={py(v)}
              x2={W - R}
              y2={py(v)}
              stroke="#f0eeea"
            />
            <text x={L - 8} y={py(v)} fontSize={10} fill="#a8a29e" textAnchor="end" dominantBaseline="central">
              {v.toFixed(1)}
            </text>
          </g>
        ))}
        {/* "knows nothing" reference */}
        <line x1={L} y1={py(LN65)} x2={W - R} y2={py(LN65)} stroke="#d6d3d1" strokeDasharray="4 4" />
        <text x={W - R} y={py(LN65) - 5} fontSize={10} fill="#a8a29e" textAnchor="end">
          random guessing (≈4.17)
        </text>

        {/* loss curves */}
        <polyline points={line("train")} fill="none" stroke="#f43f5e" strokeWidth={2} />
        <polyline points={line("val")} fill="none" stroke="#6366f1" strokeWidth={2} />

        {/* scrubber marker */}
        <line x1={px(cur.step)} y1={T} x2={px(cur.step)} y2={H - B} stroke="#a8a29e" strokeDasharray="2 3" />
        <circle cx={px(cur.step)} cy={py(cur.train)} r={4} fill="#f43f5e" />
        <circle cx={px(cur.step)} cy={py(cur.val)} r={4} fill="#6366f1" />

        {/* x labels */}
        <text x={L} y={H - 8} fontSize={10} fill="#a8a29e">
          step 0
        </text>
        <text x={W - R} y={H - 8} fontSize={10} fill="#a8a29e" textAnchor="end">
          {maxStep.toLocaleString()}
        </text>
      </svg>

      {/* scrubber controls */}
      <div className="mt-3 flex items-center gap-3">
        <button
          onClick={() => {
            if (idx >= history.length - 1) setIdx(0);
            setPlaying((p) => !p);
          }}
          className="rounded-lg bg-amber-500 px-4 py-1.5 text-sm font-semibold text-white hover:bg-amber-400"
        >
          {playing ? "Pause" : "▶ Play"}
        </button>
        <input
          type="range"
          min={0}
          max={history.length - 1}
          value={idx}
          onChange={(e) => {
            setPlaying(false);
            setIdx(+e.target.value);
          }}
          className="flex-1 accent-amber-500"
        />
        <span className="w-28 text-right font-mono text-sm text-stone-600">
          step {cur.step.toLocaleString()}
        </span>
      </div>

      <div className="mt-2 flex gap-4 font-mono text-sm">
        <span className="text-rose-600">train {cur.train.toFixed(3)}</span>
        <span className="text-indigo-600">val {cur.val.toFixed(3)}</span>
      </div>

      {/* what the model writes at this point in training (hidden when a parent
          renders the sample itself so it can carry into the generation canvas) */}
      {!hideSample && (
        <div className="mt-3">
          <p className="mb-1 text-xs text-stone-400">
            what the model generates at step {cur.step.toLocaleString()}:
          </p>
          <pre className="max-h-32 overflow-hidden whitespace-pre-wrap rounded-xl border border-stone-200 bg-stone-50 p-3 font-mono text-[13px] leading-relaxed text-stone-700">
            {curSample?.text ?? ""}
          </pre>
        </div>
      )}
    </div>
  );
}
